### ISSUE TITLE
Add markdown linter

### ISSUE THREAD

**Issue by marcoieni** [VSpaceCode/vspacecode.github.io#22]
## Problem

Right now we have to manually check if markdown is correct.

## Solution

In the [rust patterns book](https://github.com/rust-unofficial/patterns) we setup an action that checks markdown correctness.
Here it is:

https://github.com/rust-unofficial/patterns/blob/ad52fcb8eaff04df988997614ac035d51ab0c602/.github/workflows/ci.yml#L45-L53

It uses [markdownlint](https://github.com/DavidAnson/markdownlint) in the background and the rules customization is done in [this](https://github.com/rust-unofficial/patterns/blob/master/.markdownlint.yaml) file.

If you like the idea I can set up this for this repo, too.

**Comment by stevenguh** [comment]
That would be awesome!

Something related, I thought about using [prettier](https://prettier.io) in the repos that have js/ts code to address this https://github.com/VSpaceCode/VSpaceCode/issues/114 like how [VSCodeVim does it](https://github.com/VSCodeVim/Vim/blob/master/.github/workflows/build.yml#L29-L36). (prettier can prettify md files as well)

Although, prettifying is a different than linting, I am wondering should we also have a prettifying process in addition to the lint you are adding?

**Comment by marcoieni** [comment]
In the CI prettier would just check if the code is formatted correctly, right?
If so, than it is the same use case of markdownlint for us.
But with markdownlint you can decide which [rules](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md) to follow and in this way you create the style you like. Can you do this with prettier for markdown?

Anyway I like the idea of using prettier for js/ts in our repos for checking that code is formatted correctly :)

**Comment by stevenguh** [comment]
> In the CI prettier would just check if the code is formatted correctly, right?

The way vscode vim use it in their CI will format it and rewrite the commit I think.

> But with markdownlint you can decide which rules to follow and in this way you create the style you like. Can you do this with prettier for markdown?

I think prettier is [fairly limited](https://prettier.io/blog/2017/11/07/1.8.0.html#markdown-support) for their markdown formatting and doesn't seem to provide that much config intentionally.

It seems like lint and formatting are separate process that we probably should have prettier and linting like the CI in vscode repo. Since this feature request is only for listing, I am open to try the markdown lint :)
