### ISSUE TITLE
Document how to use vim remap

### ISSUE THREAD

**Issue by stevenguh** [VSpaceCode/vspacecode.github.io#3]
Split from https://github.com/VSpaceCode/VSpaceCode/issues/90#issuecomment-694827417

We are not documenting how to use `vim.remap` in overrides and in the regular binding

There are two primary ways to use it:
https://github.com/VSpaceCode/VSpaceCode/blob/v0.7.5/package.json#L106-L117
https://github.com/VSpaceCode/VSpaceCode/blob/v0.7.5/package.json#L1044-L1056

**Comment by stevenguh** [comment]
Base on https://github.com/VSpaceCode/vscode-which-key/issues/15#issuecomment-695191599 , we should also mention if a user changed it's leader key, the default easy motion command might not work.

**Comment by marcoieni** [comment]
This should be closed because #15 has been merged, right?

**Comment by stevenguh** [comment]
right. thanks for the reminder.
