### ISSUE TITLE
Branch alignment problem

### ISSUE THREAD

**Issue by marcoieni** [VSpaceCode/vspacecode.github.io#34]
## Bug description

I wanted to do a PR against vspacecode-next, but right now it is not aligned with master.
How do you align the two? Do we have to remember to do something manual everytime there is a release?

## Screenshots

![image](https://user-images.githubusercontent.com/11428655/105778427-b1dba280-5f6c-11eb-8995-54d763d4bc39.png)

**Comment by stevenguh** [comment]
I usually manually rebase after each time I merged, I guess I forgot this time.

**Comment by stevenguh** [comment]
Should be fixed now :) Sorry about that
