### ISSUE TITLE
Document inability to get back to previous match with `,`

### ISSUE THREAD

**Issue by stevenguh** [VSpaceCode/vspacecode.github.io#36]
Fork from https://github.com/VSpaceCode/VSpaceCode/commit/a0060b5b8a104de994735515d74f9f2b3d18b9a0#commitcomment-46841828

> Just be aware, that this collides with `f{character}` and using `,` to get back to the previous match.
> 
> > After using `f{character}` you can type `;` to go to the next occurrence of the character or `,` to go to the previous one.

Although it seems to be consistent with spacemacs, we should document this behavior and its escape hatch (remove that from the `settings.json`). I am not sure if this should be document in the Major mode page or the troubleshooting page.

**Comment by marcoieni** [comment]
> Major mode page or the troubleshooting page

Maybe in major mode we mention you can use `,` to access major mode and we link to the troubleshooting page if the user wants to disable this behavior.

**Comment by stevenguh** [comment]
That sounds good. Created a PR with the suggestion.

**Comment by marcoieni** [comment]
Closed by #38
