### ISSUE TITLE
Add gif in the homepage

### ISSUE THREAD

**Issue by marcoieni** [VSpaceCode/vspacecode.github.io#4]
What do you think about adding a gif in the home page?
I was thinking to something like the readme of [VSpaceCode](https://github.com/VSpaceCode/VSpaceCode), but up to date.

**Comment by stevenguh** [comment]
That would be awesome~! The current one is definitely outdated in some sense. What should we show in the gif?
Once we have that in the website, we should able change the link of the gif in the README of VSpaceCode repo to point to the gif in this repo, so we don't host large binary file in the VSpaceCode repo.

**Comment by marcoieni** [comment]
![Peek 2020-09-19 09-18](https://user-images.githubusercontent.com/11428655/93661623-74fd1d80-fa59-11ea-9ca2-397996f593e5.gif)

What do you think about this one?

**Comment by stevenguh** [comment]
Looks great over all. I wish the key display is easier to follow somehow? Maybe a more frequent clearing of the on screen key combo?

I like that the file is relatively small (<5MB) I had to do some weird compression on the size of the current gif down.

**Comment by marcoieni** [comment]
> I like that the file is relatively small (<5MB) I had to do some weird compression on the size of the current gif down.

I am using [peek](https://github.com/phw/peek).

> I wish the key display is easier to follow somehow

Tell me if this is better:

![Peek 2020-09-19 09-50](https://user-images.githubusercontent.com/11428655/93662120-d7f0b380-fa5d-11ea-9e6e-12859384586b.gif)

**Comment by stevenguh** [comment]
It looks perfect. Thank you for creating an gif. I am sorry I am kind of nit picking😅, can we not cut the status bar in half?

**Comment by marcoieni** [comment]
man.. 😂

![Peek 2020-09-19 10-12](https://user-images.githubusercontent.com/11428655/93662493-d379ca00-fa60-11ea-821a-062863fe06c5.gif)

**Comment by stevenguh** [comment]
I am sorry 😅 ship it 🚀

**Comment by marcoieni** [comment]
I am not a frontend developer, if you want you can adjust the way it looks :)

**Comment by stevenguh** [comment]
I updated the layout a little bit and added a star button :) Hopefully that works a little bit better

**Comment by marcoieni** [comment]
On desktop it looks better, but there are some issues with mobile, I opened #5
