### ISSUE TITLE
optimize interface for mobile

### ISSUE THREAD

**Issue by marcoieni** [VSpaceCode/vspacecode.github.io#5]
![image](https://user-images.githubusercontent.com/11428655/93707787-c2e55480-fb31-11ea-8a72-fa1bde96d1ba.png)

This is how I see the website on my 5" display (I took the screenshot from desktop by shrinking the window size, but it's the same)

Here are my complaints:
- [ ] "Get Started" button is attached to the left
- [ ] the "VSpaceCode" title is on two lines, but potentially it could fit in one line
- [ ] the gif is not centered

**Comment by stevenguh** [comment]
Good catch. This should be fixed on 7ccb05900afc7366dd1dc2f6790ab6027525bb5d

**Comment by marcoieni** [comment]
Yes, now it looks perfect on my device!
